name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ davidraj02 }}
        password: ${{ dckr_pat_Q2MNRr45HKv-cDhWGOVKedKTDNk}}

    - name: Build Docker image
      run: docker build -t ${{ davidraj02 }}/my-app:latest .

    - name: Push Docker image
      run: docker push ${{ davidraj02}}/my-app:latest

